apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-b3qv
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0011-tenant/tkrw-pr712-0075-0011-app/devfile-sample-b3qv@sha256:f6d801e881bf5ee29a137b6640b887b3aab41ef6bb6dcba7967586b03f5879fd
        name: my-nodejs
        resources: {}
status: {}
